const fs = require('fs');
const path = require('path');

const taPath = path.resolve(__dirname, 'app/src/locales/ta/translation.json');
const enPath = path.resolve(__dirname, 'app/src/locales/en/translation.json');

const taTranslations = {
  "alert_center_title": "பண்ணை எச்சரிக்கை மற்றும் பரிந்துரை மையம்",
  "alert_center_subtitle": "பால் உற்பத்தி குறைவு, சுகாதார மதிப்பெண்கள் மற்றும் வரவிருக்கும் தேதிகளின் அடிப்படையில் AI ரிஸ்க் இன்ஜினரால் உருவாக்கப்படும் நுண்ணறிவு.",
  "all_clear": "எல்லாம் பாதுகாப்பானது!",
  "no_anomalies": "உங்கள் கால்நடைகளில் தீவிர முரண்பாடுகள் அல்லது சுகாதார அபாயங்கள் கண்டறியப்படவில்லை.",
  "recommended_action": "பரிந்துரைக்கப்பட்ட செயல்",
  "animal_prefix": "கால்நடை",
  "data_quality": "தரவு தரம்"
};

const enTranslations = {
  "alert_center_title": "Farm Alert & Recommendation Center",
  "alert_center_subtitle": "Actionable intelligence generated by the AI Risk Engine based on milk drops, health scores, and upcoming dates.",
  "all_clear": "All Clear!",
  "no_anomalies": "No critical anomalies or health risks detected in your herd.",
  "recommended_action": "Recommended Action",
  "animal_prefix": "Animal",
  "data_quality": "Data Quality"
};

function updateJson(filePath, newTranslations) {
  const content = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(content);
  
  if (!json.livestock) json.livestock = {};
  
  Object.assign(json.livestock, newTranslations);
  
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
  console.log('Updated ' + filePath);
}

updateJson(taPath, taTranslations);
updateJson(enPath, enTranslations);
