import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { FaBell, FaExclamationTriangle, FaCheckCircle, FaClipboardList, FaInfoCircle } from 'react-icons/fa';

const buildApiUrl = (path) => {
  return `${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'}/api${path}`;
};

const AlertCenter = () => {
  const { t } = useTranslation();
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      
      const [assetRes, qualityRes] = await Promise.all([
        fetch(buildApiUrl('/livestock/asset-dashboard'), { headers: { 'Authorization': `Bearer ${token}` } }),
        fetch(buildApiUrl('/intelligence/quality'), { headers: { 'Authorization': `Bearer ${token}` } })
      ]);

      let combinedAlerts = [];

      if (assetRes.ok) {
        const json = await assetRes.json();
        combinedAlerts = [...(json.alerts || [])];
      }

      if (qualityRes.ok) {
        const qualityJson = await qualityRes.json();
        const qualityAlerts = (qualityJson.issues || []).map(issue => ({
          animal: issue.animalId ? `${t('livestock.animal_prefix', 'Animal')} ${issue.animalId}` : t('livestock.data_quality', 'Data Quality'),
          severity: issue.severity === 'CRITICAL' ? 'Critical' : issue.severity === 'HIGH' ? 'Warning' : 'Info',
          message: issue.explanation,
          action: issue.action,
          isDataQuality: true
        }));
        combinedAlerts = [...combinedAlerts, ...qualityAlerts];
      }

      // Sort so Critical comes first
      combinedAlerts.sort((a, b) => {
        const sevScore = { 'Critical': 3, 'Warning': 2, 'Info': 1 };
        return (sevScore[b.severity] || 0) - (sevScore[a.severity] || 0);
      });

      setAlerts(combinedAlerts);
    } catch (err) {
      console.error('Error fetching alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center items-center h-64"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-red-500"></div></div>;
  }

  return (
    <div className="space-y-6 animate-fade-in max-w-4xl mx-auto">
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
        <h2 className="text-2xl font-bold text-gray-800 mb-2 flex items-center">
          <FaBell className="text-red-500 mr-3" />
          {t('livestock.alert_center_title', 'Farm Alert & Recommendation Center')}
        </h2>
        <p className="text-gray-500 mb-6">{t('livestock.alert_center_subtitle', 'Actionable intelligence generated by the AI Risk Engine based on milk drops, health scores, and upcoming dates.')}</p>
        
        {alerts.length === 0 ? (
          <div className="text-center py-12 bg-gray-50 rounded-lg border border-dashed border-gray-200">
            <FaCheckCircle className="text-green-500 text-5xl mx-auto mb-4" />
            <h3 className="text-xl font-bold text-gray-700">{t('livestock.all_clear', 'All Clear!')}</h3>
            <p className="text-gray-500">{t('livestock.no_anomalies', 'No critical anomalies or health risks detected in your herd.')}</p>
          </div>
        ) : (
          <div className="space-y-4">
            {alerts.map((alert, idx) => (
              <div key={idx} className={`p-5 rounded-xl border flex items-start ${
                alert.severity === 'Critical' ? 'bg-red-50 border-red-200' : 
                alert.severity === 'Warning' ? 'bg-orange-50 border-orange-200' : 
                'bg-blue-50 border-blue-200'
              }`}>
                <div className="mt-1 mr-4">
                  {alert.severity === 'Critical' ? <FaExclamationTriangle className="text-red-500 text-2xl"/> : 
                   alert.severity === 'Warning' ? <FaExclamationTriangle className="text-orange-500 text-2xl"/> : 
                   <FaInfoCircle className="text-blue-500 text-2xl"/>}
                </div>
                <div className="flex-1">
                  <h4 className="text-lg font-bold text-gray-800 mb-1">{alert.animal}</h4>
                  <p className="text-gray-700 mb-3">{alert.message}</p>
                  
                  <div className="bg-white bg-opacity-60 rounded p-3 border border-gray-200">
                    <span className="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">{t('livestock.recommended_action', 'Recommended Action')}</span>
                    <span className="font-bold text-blue-800 flex items-center">
                      <FaClipboardList className="mr-2"/> {alert.action}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default AlertCenter;
